### ISSUE TITLE
Trouble with insecure MQTT connection

### ISSUE THREAD

**Issue by mfjonesy** [asymworks/AirQualityESP#1]
Thank you so much for this cool project! I'm having trouble connecting to the MQTT server (Home Assistant) unsecured. I've commented out the MQTT_SECURE in config.h. Do I also need to comment out the MQTT fingerprint in config.cpp?

![mqtt](https://user-images.githubusercontent.com/52838141/153278052-54a0f525-93e4-43fc-b6dc-f559e556a6cc.png)

Also I'm not sure why it's trying to connect to the MQTT server using that username, I'm not sure where that's coming from. Any thoughts? Thanks!

**Comment by asymworks** [comment]
Hi @mfjonesy, I think it was an error in mqtt.cpp where the port was hard-coded to be the MQTT secure port 8883.  I just pushed an update that should fix it and use port 1883 for insecure connections; can you re-download and see if that fixes it?

The 000001c187be is the MQTT Client ID, not the username.  It's basically just the serial number of your SGP30 sensor, and is used as a unique ID for the sensor data MQTT topic (and the Home Assistant sensor entity as well).  The MQTT user name will be pulled from config.cpp and won't be echoed to the serial terminal.

**Comment by mfjonesy** [comment]
Now I'm getting a build error that says "undefined reference to mqtt_port". When I try to hard-code it to 1883 I can build it successfully but I still get the same result when I run it.

I also have this error in my mqtt.cpp but I'm not sure if it's related
![mqtt1](https://user-images.githubusercontent.com/52838141/153287318-27725ea7-fdff-4d18-b355-76c9d5e7342c.png)

**Comment by asymworks** [comment]
Hmm, OK.  Let me dig into the build errors a bit, since I don't see it on my end.  It probably should have worked with a hard-coded 1883 port, though.  Were there any clues in your MQTT logs?

**Comment by mfjonesy** [comment]
I'm not seeing any clues in my MQTT logs unfortunately. Thanks for helping me figure this out!

**Comment by asymworks** [comment]
OK, I think I've solved the build error and the insecure MQTT connection.  I was able to reproduce the linker error, so that should be fixed, and it now connects to a test MQTT server using the insecure connection, so hopefully that will solve it for you.  Give it a try and let me know if you still have issues!

**Comment by mfjonesy** [comment]
Progress is being made! I'm still getting the same build error with the undefined reference for 'mqtt_port' but it works if I hard code it 1883. Now when I run it looks like it's connecting but it's not showing up in my Home Assistant using the native MQTT integration. I have auto discovery enabled and I've had other devices auto discover just fine. I'm not seeing any clues in the logs either. Any thoughts on how to get it in to Home Assistaant? Here's the serial output
![mqtt2](https://user-images.githubusercontent.com/52838141/153334736-dbf44e89-6765-4f18-9b39-f3212ad9c1d5.png)

**Comment by asymworks** [comment]
Great!  Odd that the linker error still shows up, but I'm glad that hard-coding the port is working at least.  If you go into the HA MQTT configuration panel and subscribe to `homeassistant/sensor/#` and reboot the sensor, do you see the auto-discovery messages?  Or if you subscribe to `sensor/aq/#` you should see the sensor data every minute or so.  

If the MQTT messages aren't showing up at all, I would guess it's related to MQTT permissions somehow.  What MQTT broker are you using?

**Comment by mfjonesy** [comment]
Yes I can see the auto-discovery messages  using that method. This is what I see

![mqtt2](https://user-images.githubusercontent.com/52838141/153449773-8564df64-9794-47f8-acf2-37976514874c.png)

I can see the sensor data as well.

And I'm using this broker https://github.com/home-assistant/addons/tree/master/mosquitto

**Comment by asymworks** [comment]
OK, I might see the issue - the MQTT messages are getting cut off.  I think I might have had to patch the Adafruit MQTT library to fix that, but there is probably a less hacky way to do it.  I won't be able to do more debugging and test until later today, but I think we're getting close to solving it.

**Comment by asymworks** [comment]
I wasn't able to see an easy way to get around the message length limit without patching the Adafruit library, so I probably have a longer-term project to swap it out with a better option.  In the meantime, if you open the Adafruit_MQTT.h file in the library and change the `MAXBUFFERSIZE` define (line 110) to 300, it should then work.  If you're using PlatformIO, that file should be in `.pio/libdeps/nodemcuv2/Adafruit MQTT Library`.  

I'm going to close this issue and open a new one to track the short message length issue, since I think the insecure connection itself is resolved.

**Comment by asymworks** [comment]
Closing this with b9b909d, follow-on about MQTT message issues in #2
